project_name: go-cve-dictionary
release:
  github:
    owner: vulsio
    name: go-cve-dictionary
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.Commit}}
  binary: go-cve-dictionary
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
